Repository bluewave-labs/datahall, pull requests merged in 2024-11, with the labels that each got.

#80 bug/Settings and Invite modal fixes
  Client/src/app/settings/components/BrandingSetting.tsx
  Client/src/components/Dropdown.tsx
  Client/src/components/ModalWrapper.tsx
Labels: Bug, Refactor

#84 Feature/Update document icons
  Client/public/assets/icons/documentPage/audio-icon.svg
  Client/public/assets/icons/documentPage/general-icon.svg
  Client/public/assets/icons/documentPage/image-icon.svg
  Client/public/assets/icons/documentPage/pdf-icon.svg
  Client/public/assets/icons/documentPage/ppt-icon.svg
  Client/public/assets/icons/documentPage/txt-icon.svg
  Client/public/assets/icons/documentPage/video-icon.svg
  Client/public/assets/icons/documentPage/word-icon.svg
  Client/public/assets/icons/documentPage/xlsx-icon.svg
  Client/public/assets/icons/documentPage/zip-icon.svg
  Client/src/app/documents/components/DocumentsTable.tsx
  Client/src/app/documents/components/DocumentsTableRow.tsx
  Client/src/data/dummyDocuments.ts
Labels: New Feature

#82 bug/Documents, Profile and Pagination fixes
  Client/public/assets/icons/pagination/ArrowBackIcon.tsx
  Client/public/assets/icons/pagination/ArrowForwardIcon.tsx
  Client/src/app/documents/components/DocumentsTableRow.tsx
  Client/src/app/documents/components/DragAndDropBox.tsx
  Client/src/app/documents/page.tsx
  Client/src/app/profile/page.tsx
  Client/src/components/Paginator.tsx
Labels: Bug

#89 Auth UI V2.0 - Integration with the Backend
  Client/package-lock.json
  Client/package.json
  Client/public/assets/Background.tsx
  Client/public/assets/BluewaveLogo.tsx
  Client/public/assets/doc-background.svg
  Client/src/app/AuthWrapper.tsx
  Client/src/app/api/auth/[...nextauth]/route.ts
  Client/src/app/api/auth/resetPass/route.ts
  Client/src/app/api/auth/verify-email/route.ts
  Client/src/app/auth/account-created/loading.tsx
  Client/src/app/auth/account-created/page.tsx
  Client/src/app/auth/forgot-password/loading.tsx
  Client/src/app/auth/forgot-password/page.tsx
  Client/src/app/auth/password-reset-confirm/loading.tsx
  Client/src/app/auth/reset-password/loading.tsx
  Client/src/app/auth/reset-password/page.tsx
  Client/src/app/auth/sign-in/loading.tsx
  Client/src/app/auth/sign-in/page.tsx
  Client/src/app/auth/sign-up/loading.tsx
  Client/src/app/auth/sign-up/page.tsx
  Client/src/app/documents/components/ActionMenu.tsx
  Client/src/app/documents/loading.tsx
  Client/src/app/layout.tsx
  Client/src/app/layout/DropdownMenu.tsx
  Client/src/app/loading.tsx
  Client/src/app/providers.tsx
  Client/src/app/team/components/TeamClient.tsx
  Client/src/middleware.ts
Labels: New Feature, Core

#91 Auth UI V2.1
  Client/src/app/AuthWrapper.tsx
  Client/src/app/api/auth/register/route.ts
  Client/src/app/auth/account-created/page.tsx
  Client/src/app/auth/components/AuthFormWrapper.tsx
  Client/src/app/auth/components/AuthInput.tsx
  Client/src/app/auth/components/PasswordValidation.tsx
  Client/src/app/auth/forgot-password/page.tsx
  Client/src/app/auth/password-reset-confirm/page.tsx
  Client/src/app/auth/reset-password/page.tsx
  Client/src/app/auth/sign-in/page.tsx
  Client/src/app/auth/sign-up/page.tsx
  Client/src/components/LoadingButton.tsx
  Client/src/hooks/useAuthForm.ts
  Client/src/hooks/useFormData.ts
Labels: Refactor, Core, Frontend

#94 bug/Fixing DropdownMenu Component
  Client/src/app/layout/DropdownMenu.tsx
Labels: Bug, Frontend

#87 Fix for Issue #66, #67, #68, #70, #71 and #74
  Client/public/assets/Background.tsx
  Client/public/assets/icons/documentPage/ArrowLeft.tsx
  Client/src/app/AuthWrapper.tsx
  Client/src/app/contacts/components/ContactsTable.tsx
  Client/src/app/contacts/loading.tsx
  Client/src/app/documents/components/CreateLink.tsx
  Client/src/app/documents/components/CustomAccordian.tsx
  Client/src/app/documents/components/DragAndDropBox.tsx
  Client/src/app/documents/components/LinkDetailsAccordion.tsx
  Client/src/app/documents/page.tsx
  Client/src/app/layout.tsx
  Client/src/app/layout/Sidebar.tsx
  Client/src/app/profile/loading.tsx
  Client/src/app/profile/page.tsx
  Client/src/app/settings/components/BrandingSetting.tsx
  Client/src/app/settings/loading.tsx
  Client/src/app/settings/page.tsx
  Client/src/app/team/components/OrganizationName.tsx
  Client/src/app/team/components/TeamClient.tsx
  Client/src/app/team/components/UserTable.tsx
  Client/src/app/team/loading.tsx
  Client/src/app/team/page.tsx
  Client/src/components/CustomTextField.tsx
  Client/src/components/Dropdown.tsx
  Client/src/components/ModalWrapper.tsx
  Client/src/components/Toast.tsx
  Client/src/utils/theme/globalTheme.ts
Labels: Bug, Frontend

#85 bug/Sidebar fix
  Client/public/assets/icons/breadcrumb/HomeIcon.tsx
  Client/public/assets/icons/breadcrumb/breadcrumb-home-icon.svg
  Client/public/assets/icons/sidebar/ContactsIcon.tsx
  Client/public/assets/icons/sidebar/DocumentsIcon.tsx
  Client/public/assets/icons/sidebar/LogOutIcon.tsx
  Client/public/assets/icons/sidebar/ProfileIcon.tsx
  Client/public/assets/icons/sidebar/SettingsIcon.tsx
  Client/public/assets/icons/sidebar/TeamIcon.tsx
  Client/public/assets/icons/sidebar/sidebar-contacts-icon.svg
  Client/public/assets/icons/sidebar/sidebar-documents-icon.svg
  Client/public/assets/icons/sidebar/sidebar-log-out-icon.svg
  Client/public/assets/icons/sidebar/sidebar-profile-icon.svg
  Client/public/assets/icons/sidebar/sidebar-settings-icon.svg
  Client/public/assets/icons/sidebar/sidebar-team-icon.svg
  Client/src/app/documents/components/DocumentsTableRow.tsx
  Client/src/app/layout/DropdownMenu.tsx
  Client/src/app/layout/Sidebar.tsx
  Client/src/components/Breadcrumb.tsx
Labels: Bug, Refactor, Frontend

#98 Minor Bug Fix with `Dropdown.tsx` and it's usage
  Client/src/app/documents/components/CustomAccordian.tsx
  Client/src/app/documents/components/DocumentsTableHeader.tsx
  Client/src/app/documents/components/DocumentsTableRow.tsx
  Client/src/app/documents/components/SendingAccordion.tsx
  Client/src/app/profile/page.tsx
  Client/src/components/Dropdown.tsx
  Client/src/components/ModalWrapper.tsx
Labels: Bug, Frontend

#100 Feature/Link feature to documents
  Client/public/assets/icons/documentPage/LinkIcon.tsx
  Client/src/app/documents/components/DocumentsTable.tsx
  Client/src/app/documents/components/DocumentsTableHeader.tsx
  Client/src/app/documents/components/DocumentsTableRow.tsx
  Client/src/data/dummyDocuments.ts
Labels: New Feature, Frontend
