Repository bluewave-labs/datahall, pull requests merged in 2024-12, with the labels that each got.

#101 Feature/Implemented files details section
  Client/public/assets/icons/documentPage/CopyIcon.tsx
  Client/src/app/documents/components/DocumentsTable.tsx
  Client/src/app/documents/components/DocumentsTableHeader.tsx
  Client/src/app/documents/document-details/components/CustomBarChart.tsx
  Client/src/app/documents/document-details/components/DocumentDetailsClient.tsx
  Client/src/app/documents/document-details/components/DocumentDetailsTable.tsx
  Client/src/app/documents/document-details/components/DocumentDetailsTableHeader.tsx
  Client/src/app/documents/document-details/components/DocumentDetailsTableRow.tsx
  Client/src/app/documents/document-details/components/FilterToggle.tsx
  Client/src/app/documents/document-details/page.tsx
  Client/src/data/dummyDocuments.ts
  Client/src/utils/theme/globalTheme.ts
Labels: New Feature, Frontend

#103 refactor/Sidebar refactoring
  Client/src/app/AuthWrapper.tsx
  Client/src/app/layout/Sidebar.tsx
Labels: Refactor, Frontend

#99 Fix issues from #92 and #93
  Client/lib/prisma.ts
  Client/package-lock.json
  Client/package.json
  Client/prisma/migrations/20241112161117_add_first_and_last_name/migration.sql
  Client/prisma/schema.prisma
  Client/src/app/AuthWrapper.tsx
  Client/src/app/api/auth/[...nextauth]/route.ts
  Client/src/app/api/auth/register/route.ts
  Client/src/app/api/auth/resetPass/route.ts
  Client/src/app/api/auth/resetPassForm/route.ts
  Client/src/app/api/auth/verify-email/route.ts
  Client/src/app/auth/account-created/page.tsx
  Client/src/app/auth/check-email/page.tsx
  Client/src/app/auth/components/ForgotPasswordEmail.tsx
  Client/src/app/auth/components/WelcomeEmail.tsx
  Client/src/app/auth/forgot-password/page.tsx
  Client/src/app/auth/password-reset-confirm/page.tsx
  Client/src/app/auth/reset-password/page.tsx
  Client/src/app/register/page.tsx
  Client/src/app/resetPass/page.jsx
  Client/src/app/resetPassForm/[token]/page.tsx
  Client/src/app/signIn/page.tsx
  Client/src/middleware.ts
Labels: New Feature, Refactor, Backend, Core

#104 Implement Document Management System Backend
  Client/.gitignore
  Client/lib/middleware/authenticate.ts
  Client/package-lock.json
  Client/package.json
  Client/prisma/schema.prisma
  Client/src/app/api/documents/delete/route.ts
  Client/src/app/api/documents/list/route.ts
  Client/src/app/api/documents/upload/route.ts
  Client/src/app/contacts/components/ContactsTable.tsx
  Client/src/app/contacts/components/ContactsTableRow.tsx
  Client/src/app/documents/components/CreateLink.tsx
  Client/src/app/documents/components/DocumentsTable.tsx
  Client/src/app/documents/components/DocumentsTableHeader.tsx
  Client/src/app/documents/components/DocumentsTableRow.tsx
  Client/src/app/documents/components/DragAndDropBox.tsx
  Client/src/app/documents/document-details/components/DocumentDetailsClient.tsx
  Client/src/app/documents/document-details/components/DocumentDetailsTableRow.tsx
  Client/src/app/documents/page.tsx
  Client/src/app/layout/Sidebar.tsx
  Client/src/app/team/components/TeamClient.tsx
  Client/src/app/team/components/UserTable.tsx
  Client/src/data/dummyContacts.ts
  Client/src/data/dummyDocuments.ts
  Client/src/data/dummyTeams.ts
  Client/src/providers/storage/supabase/supabaseProvider.ts
  Client/src/services/documentService.ts
  Client/src/services/storageService.ts
  Client/src/utils/shared/models.ts
  Client/src/utils/shared/utils.ts
Labels: New Feature, Backend, Core

#119 Refactor/toast notification
  Client/src/app/documents/components/DragAndDropBox.tsx
  Client/src/app/profile/components/ProfileForm.tsx
  Client/src/app/providers.tsx
  Client/src/components/Toast.tsx
  Client/src/hooks/useToast.ts
  Client/src/providers/toast/ToastProvider.tsx
  Client/src/providers/toast/toastTypes.ts
Labels: Refactor, Frontend

#118 Auth V3 Complete
  Client/prisma/schema.prisma
  Client/public/assets/Background.tsx
  Client/src/app/api/auth/[...nextauth]/route.ts
  Client/src/app/auth/components/AuthFormWrapper.tsx
  Client/src/app/auth/forgot-password/page.tsx
  Client/src/app/auth/reset-password/page.tsx
  Client/src/app/auth/sign-up/page.tsx
  Client/src/app/documents/components/DragAndDropBox.tsx
  Client/src/components/NavLink.tsx
  Client/src/hooks/useAuthForm.ts
  Client/src/providers/auth/AuthWrapper.tsx
Labels: Refactor, Backend, Frontend

#106 Integrate DELETE API with Documents UI
  Client/.gitignore
  Client/src/app/api/documents/delete/[documentId]/route.ts
  Client/src/app/api/documents/delete/route.ts
  Client/src/app/documents/components/ActionMenu.tsx
  Client/src/app/documents/components/DocumentsTable.tsx
  Client/src/app/documents/components/DocumentsTableRow.tsx
Labels: New Feature, Backend, Core

#125 Refactor/Updating toast usages
  Client/src/app/auth/forgot-password/page.tsx
  Client/src/app/documents/components/DragAndDropBox.tsx
  Client/src/app/documents/document-details/components/DocumentDetailsTableRow.tsx
  Client/src/app/profile/components/ProfileForm.tsx
  Client/src/app/settings/components/BrandingSetting.tsx
Labels: New Feature, Refactor, Frontend

#126 Feat/change password
  Client/src/app/api/profile/changePassword/route.ts
  Client/src/app/profile/components/PasswordForm.tsx
Labels: New Feature, Backend, Core

#129 feat/new upload modal
  Client/src/app/documents/components/DragAndDropBox.tsx
  Client/src/app/profile/components/ProfileForm.tsx
  Client/src/app/settings/components/BrandingSetting.tsx
  Client/src/components/CustomCircularProgress.tsx
  Client/src/components/CustomUploader.tsx
  Client/src/components/ModalWrapper.tsx
  Client/src/hooks/useFileInfo.ts
Labels: New Feature, Frontend, UX/UI Change

#128 Feat/edit profile
  Client/.gitignore
  Client/src/app/api/profile/changeName/route.ts
Labels: New Feature, Backend
