Repository bluewave-labs/datahall, pull requests merged in 2024-10, with the labels that each got.

#45 Refactor/#40-sepidehs-section
  Client/public/assets/icons/sidebar/sidebar-documents-icon.svg
  Client/public/assets/icons/sidebar/sidebar-log-out-icon.svg
  Client/public/assets/icons/sidebar/sidebar-password-icon.svg
  Client/public/assets/icons/sidebar/sidebar-profile-icon.svg
  Client/public/assets/icons/sidebar/sidebar-settings-icon.svg
  Client/public/assets/icons/sidebar/sidebar-team-icon.svg
  Client/public/assets/icons/uploadModel/upload-cloud-icon.svg
  Client/src/Components/DeleteConfirmationModal.tsx
  Client/src/Components/ModalWrapper.tsx
  Client/src/Components/UploadModal.tsx
  Client/src/app/documents/components/ActionMenu.tsx
  Client/src/app/documents/components/DragAndDropBox.tsx
  Client/src/app/documents/page.tsx
  Client/src/app/profile/components/ProfileForm.tsx
  package-lock.json
Labels: Bug

#47 Feature/Settings Page
  Client/package-lock.json
  Client/package.json
  Client/src/app/settings/components/BrandingSetting.tsx
  Client/src/app/settings/components/ColorPickerBox.tsx
  Client/src/app/settings/components/SettingsTabs.tsx
  Client/src/app/settings/page.tsx
Labels: New Feature

#48 Link Creation Modal
  Client/.gitignore
  Client/.prettierrc
  Client/public/assets/icons/documentPage/Checked.tsx
  Client/public/assets/icons/documentPage/CopyIcon.tsx
  Client/public/assets/icons/documentPage/Unchecked.tsx
  Client/src/app/documents/components/ActionMenu.tsx
  Client/src/app/documents/components/CreateLink.tsx
  Client/src/app/documents/components/CustomAccordian.tsx
  Client/src/app/documents/components/DocumentsTable.tsx
  Client/src/app/documents/components/DocumentsTableHeader.tsx
  Client/src/app/documents/components/DocumentsTableRow.tsx
  Client/src/app/documents/components/DragAndDropBox.tsx
  Client/src/app/documents/components/LinkDetailsAccordion.tsx
  Client/src/app/documents/components/SendingAccordion.tsx
  Client/src/app/documents/components/SharingOptionsAccordion.tsx
  Client/src/app/layout.tsx
  Client/src/app/profile/components/ProfileForm.tsx
  Client/src/components/CustomCheckbox.tsx
  Client/src/components/CustomTextField.tsx
  Client/src/components/Dropdown.tsx
  Client/src/utils/theme/globalTheme.ts
Labels: New Feature

#58 Feature/Invite new team member
  Client/src/app/team/components/TeamClient.tsx
  Client/src/components/ModalWrapper.tsx
Labels: New Feature

#56 Authentication Flow V1.0
  Client/.env
  Client/.prettierrc
  Client/package-lock.json
  Client/package.json
  Client/public/assets/icons/auth/CheckIcon.tsx
  Client/public/assets/icons/auth/KeyIcon.tsx
  Client/public/assets/icons/auth/LockIcon.tsx
  Client/public/assets/icons/auth/MailIcon.tsx
  Client/public/assets/icons/sidebar/AnimatedArrowIcon.tsx
  Client/public/assets/icons/sidebar/SidebarTitle.tsx
  Client/public/assets/icons/uploadModal/upload-cloud-01.svg
  Client/src/app/auth/account-created/page.tsx
  Client/src/app/auth/email-sent/page.tsx
  Client/src/app/auth/forgot-password/page.tsx
  Client/src/app/auth/password-reset-confirm/page.tsx
  Client/src/app/auth/reset-password/page.tsx
  Client/src/app/auth/sign-in/page.tsx
  Client/src/app/auth/sign-up/page.tsx
  Client/src/components/NavLink.tsx
  Client/src/components/sidebar/DropdownMenu.tsx
  Client/src/utils/theme/globalTheme.ts
Labels: New Feature, Core

#61 Feature/Reusable Toast component
  Client/src/components/Toast.tsx
  Client/src/hooks/useToast.ts
  Client/src/utils/theme/globalTheme.ts
Labels: New Feature

#63 Refactored Code for Improved Code Quality and Performance
  Client/package-lock.json
  Client/package.json
  Client/src/app/contacts/page.tsx
  Client/src/app/documents/components/ActionMenu.tsx
  Client/src/app/documents/components/CreateLink.tsx
  Client/src/app/documents/components/DragAndDropBox.tsx
  Client/src/app/documents/page.tsx
  Client/src/app/layout/DropdownMenu.tsx
  Client/src/app/layout/Sidebar.tsx
  Client/src/app/profile/components/PasswordForm.tsx
  Client/src/app/profile/components/ProfileForm.tsx
  Client/src/app/profile/profile-settings/page.tsx
  Client/src/app/providers.tsx
  Client/src/app/team/components/OrganizationName.tsx
  Client/src/app/team/components/TeamClient.tsx
  Client/src/components/Breadcrumb.tsx
  Client/src/components/ModalWrapper.tsx
  Client/src/components/sidebar/DropdownMenu.tsx
  Client/src/components/sidebar/dropdownMenu.css
  Client/src/hooks/useModal.ts
  Client/src/utils/theme/globalTheme.ts
  Client/tsconfig.json
Labels: Refactor

#64 Fixed Errors & Bugs
  Client/public/assets/BluewaveLogo.tsx
  Client/public/assets/icons/sidebar/SidebarTitle.tsx
  Client/public/assets/icons/sidebar/sidebar-title.svg
  Client/src/app/auth/account-created/page.tsx
  Client/src/app/auth/sign-in/page.tsx
  Client/src/app/auth/sign-up/page.tsx
  Client/src/app/layout/Sidebar.tsx
  Client/src/app/profile/components/ProfileForm.tsx
  Client/src/app/settings/components/BrandingSetting.tsx
  Client/src/components/ModalWrapper.tsx
Labels: Bug

#60 Refactor/register
  Client/lib/global.d.ts
  Client/lib/prisma.ts
  Client/next-auth.d.ts
  Client/package-lock.json
  Client/package.json
  Client/prisma/migrations/20241024163715_remove_unessecary_fields/migration.sql
  Client/prisma/migrations/20241024170439_change_big_int_to_int/migration.sql
  Client/prisma/migrations/migration_lock.toml
  Client/prisma/schema.prisma
  Client/src/app/api/auth/[...nextauth]/route.ts
  Client/src/app/api/auth/register/route.ts
  Client/src/app/api/auth/resetPass/route.ts
  Client/src/app/api/auth/resetPassForm/[token]/route.ts
  Client/src/app/api/send/route.ts
  Client/src/app/register/page.tsx
  Client/src/app/resetPassForm/[token]/page.tsx
  Client/src/components/email-template.tsx
  Client/tsconfig.json
Labels: Refactor

#59 Add Register Functionality and Code Refactoring.
  Client/next-auth.d.ts
  Client/package-lock.json
  Client/package.json
  Client/prisma/migrations/20241024163715_remove_unessecary_fields/migration.sql
  Client/prisma/migrations/20241024170439_change_big_int_to_int/migration.sql
  Client/prisma/migrations/migration_lock.toml
  Client/prisma/schema.prisma
  Client/src/app/api/auth/[...nextauth]/route.ts
  Client/src/app/api/auth/register/route.ts
  Client/src/app/register/page.jsx
  Client/tsconfig.json
Labels: New Feature, Refactor
