Repository bluewave-labs/datahall, pull requests merged in 2025-01, with the labels that each got.

#145 Auth Refactor
  Client/next-auth.d.ts
  Client/package-lock.json
  Client/package.json
  Client/src/app/api/auth/[...nextauth]/route.ts
  Client/src/app/api/auth/register/route.ts
  Client/src/app/api/auth/resetPass/route.ts
  Client/src/app/api/auth/resetPassForm/route.ts
  Client/src/app/api/auth/verify-email/route.ts
  Client/src/app/auth/account-created/page.tsx
  Client/src/app/auth/components/AuthInput.tsx
  Client/src/app/auth/components/PasswordValidation.tsx
  Client/src/app/auth/forgot-password/page.tsx
  Client/src/app/auth/password-reset-confirm/page.tsx
  Client/src/app/auth/reset-password/page.tsx
  Client/src/app/auth/sign-in/page.tsx
  Client/src/app/auth/sign-up/page.tsx
  Client/src/app/layout/DropdownMenu.tsx
  Client/src/app/layout/Sidebar.tsx
  Client/src/components/Toast.tsx
  Client/src/hooks/useAuthForm.ts
  Client/src/hooks/useFormData.ts
  Client/src/hooks/useValidatedFormData.ts
  Client/src/providers/toast/ToastProvider.tsx
  Client/src/utils/shared/validators.ts
Labels: Bug, New Feature, Refactor, Backend, Frontend

#146 Improved Error Handling & Real-Time Auth Validation
  Client/src/app/api/links/route.ts
  Client/src/app/auth/components/AuthInput.tsx
  Client/src/app/auth/forgot-password/page.tsx
  Client/src/app/auth/reset-password/page.tsx
  Client/src/app/auth/sign-in/page.tsx
  Client/src/app/auth/sign-up/page.tsx
  Client/src/components/FormInput.tsx
  Client/src/hooks/useAuthForm.ts
  Client/src/hooks/useFormSubmission.ts
  Client/src/services/linkService.ts
Labels: Bug, Refactor, Frontend

#147 Improved Sidebar
  Client/src/app/layout/DropdownMenu.tsx
  Client/src/app/layout/Sidebar.tsx
  Client/src/components/FormInput.tsx
Labels: Refactor, Frontend, UX/UI Change

#144 Contacts API to get the link visitors.
  Client/src/app/api/contacts/route.ts
Labels: New Feature, Backend, Core

#151 Feat/Integrate backend with profile and password tabs
  Client/src/app/auth/components/PasswordValidation.tsx
  Client/src/app/auth/reset-password/page.tsx
  Client/src/app/auth/sign-up/page.tsx
  Client/src/app/profile/components/PasswordForm.tsx
  Client/src/app/profile/components/ProfileForm.tsx
  Client/src/components/PasswordValidation.tsx
  Client/src/hooks/useValidatedFormData.ts
  Client/src/utils/shared/validators.ts
  Client/src/utils/theme/globalTheme.ts
Labels: New Feature, Backend, Core, Frontend, UX/UI Change

#159 Refactored and Cleaned up Several files
  Client/prisma/schema.prisma
  Client/public/assets/icons/auth/CheckCircleIcon.tsx
  Client/public/assets/icons/auth/XCircleIcon.tsx
  Client/public/assets/icons/documentPage/CheckIcon.tsx
  Client/src/app/auth/password-reset-confirm/page.tsx
  Client/src/app/auth/sign-up/page.tsx
  Client/src/app/contacts/components/ContactsTableRow.tsx
  Client/src/app/layout/DropdownMenu.tsx
  Client/src/app/layout/Sidebar.tsx
  Client/src/app/not-found.tsx
  Client/src/app/team/components/UserTable.tsx
  Client/src/components/ModalWrapper.tsx
  Client/src/data/dummyDocuments.ts
  Client/src/data/dummyTeams.ts
  Client/src/hooks/index.ts
  Client/src/hooks/useSort.ts
  Client/src/providers/auth/AuthWrapper.tsx
  Client/src/utils/shared/models.ts
  Client/src/utils/shared/utils.ts
  Client/src/utils/theme/customTypesTheme.d.ts
  Client/src/utils/theme/globalTheme.ts
Labels: Cleanup, Refactor

#160 Fix console warnings in link [layout]
  Client/src/app/links/[linkId]/layout.tsx
Labels: Frontend

#161 Minor ui changes in the modal which generates link
  Client/src/app/documents/components/CreateLink.tsx
Labels: Frontend

#165 Link default to public, hide options to check uncheck it
  Client/src/app/documents/components/CreateLink.tsx
Labels: Bug, Frontend

#167 Contacts page frontend integration with backend
  Client/src/app/api/contacts/route.ts
  Client/src/app/contacts/components/ContactsTable.tsx
  Client/src/app/contacts/components/ContactsTableRow.tsx
Labels: Core, Frontend

#164 Document Details Page Backend and Frontend Integration
  Client/package-lock.json
  Client/prisma/schema.prisma
  Client/public/assets/icons/auth/XCircleIcon.tsx
  Client/src/app/api/documents/[documentId]/links/[linkId]/route.ts
  Client/src/app/api/documents/[documentId]/links/route.ts
  Client/src/app/api/documents/[documentId]/route.ts
  Client/src/app/api/documents/[documentId]/visitors/route.ts
  Client/src/app/api/documents/delete/[documentId]/route.ts
  Client/src/app/api/documents/list/route.ts
  Client/src/app/api/links/route.ts
  Client/src/app/api/links/shared_access/route.ts
  Client/src/app/auth/sign-in/page.tsx
  Client/src/app/documents/[documentId]/components/CustomBarChart.tsx
  Client/src/app/documents/[documentId]/components/DocumentView.tsx
  Client/src/app/documents/[documentId]/components/FilterToggle.tsx
  Client/src/app/documents/[documentId]/components/InfoTable.tsx
  Client/src/app/documents/[documentId]/components/InfoTableHeader.tsx
  Client/src/app/documents/[documentId]/components/InfoTableRow.tsx
  Client/src/app/documents/[documentId]/loading.tsx
  Client/src/app/documents/[documentId]/not-found.tsx
  Client/src/app/documents/[documentId]/page.tsx
  Client/src/app/documents/[documentId]/view-document/page.tsx
  Client/src/app/documents/components/ActionMenu.tsx
  Client/src/app/documents/components/CreateLink.tsx
  Client/src/app/documents/components/CustomAccordion.tsx
  Client/src/app/documents/components/DocumentsTable.tsx
  Client/src/app/documents/components/DocumentsTableHeader.tsx
  Client/src/app/documents/components/DocumentsTableRow.tsx
  Client/src/app/documents/components/DragAndDropBox.tsx
  Client/src/app/documents/components/LinkDetailsAccordion.tsx
  Client/src/app/documents/components/SendingAccordion.tsx
  Client/src/app/documents/components/SharingOptionsAccordion.tsx
  Client/src/app/documents/document-details/components/CustomBarChart.tsx
  Client/src/app/documents/document-details/components/DocumentDetailsClient.tsx
  Client/src/app/documents/document-details/components/DocumentDetailsTable.tsx
  Client/src/app/documents/document-details/components/DocumentDetailsTableHeader.tsx
  Client/src/app/documents/document-details/components/DocumentDetailsTableRow.tsx
  Client/src/app/documents/document-details/page.tsx
  Client/src/app/documents/page.tsx
  Client/src/app/links/[linkId]/components/FileAccessFormModal.tsx
  Client/src/app/links/[linkId]/components/FileDisplay.tsx
  Client/src/app/not-found/page.tsx
  Client/src/components/CustomTextField.tsx
  Client/src/components/CustomUploader.tsx
  Client/src/components/FormInput.tsx
  Client/src/components/PasswordValidation.tsx
  Client/src/components/PdfViewer.tsx
  Client/src/hooks/index.ts
  Client/src/hooks/useDocumentAnalytics.ts
  Client/src/hooks/useDocumentData.ts
  Client/src/hooks/useDocumentDetail.ts
  Client/src/hooks/useFileInfo.ts
  Client/src/services/documentService.ts
  Client/src/services/linkService.ts
  Client/src/utils/shared/PdfViewer.tsx
  Client/src/utils/shared/models.ts
  Client/src/utils/shared/utils.ts
  Client/src/utils/shared/validators.ts
  package-lock.json
Labels: Cleanup, Refactor, Backend, Core, Frontend

#166 feat/creating a reusable empty state component
  Client/public/assets/icons/emptyState/EmptyStateIcon.tsx
  Client/src/app/contacts/components/ContactsTable.tsx
  Client/src/components/EmptyState.tsx
Labels: Frontend, UX/UI Change

#169 Bug/minor fixes
  Client/src/app/api/documents/[documentId]/links/route.ts
  Client/src/app/documents/[documentId]/components/InfoTableRow.tsx
  Client/src/app/documents/components/ActionMenu.tsx
  Client/src/app/documents/components/CreateLink.tsx
  Client/src/app/documents/components/CustomAccordion.tsx
  Client/src/app/documents/components/DocumentsTableRow.tsx
  Client/src/app/documents/components/LinkDetailsAccordion.tsx
  Client/src/app/documents/components/SharingOptionsAccordion.tsx
  Client/src/app/layout/DropdownMenu.tsx
  Client/src/app/layout/Sidebar.tsx
  Client/src/app/profile/components/ProfileForm.tsx
  Client/src/components/CustomCheckbox.tsx
  Client/src/components/ModalWrapper.tsx
  Client/src/hooks/useDocumentData.ts
  Client/src/utils/shared/models.ts
  Client/src/utils/theme/globalTheme.ts
Labels: Cleanup, Refactor, Frontend

#173 Temporary: fetch latest documents once upload is done
  Client/src/app/documents/components/DragAndDropBox.tsx
Labels: Bug

#171 Merge Conflict Fix - Improve consistency and responsiveness
  Client/package-lock.json
  Client/public/assets/BluewaveLogo.tsx
  Client/src/app/auth/forgot-password/page.tsx
  Client/src/app/auth/reset-password/page.tsx
  Client/src/app/auth/sign-in/page.tsx
  Client/src/app/auth/sign-up/page.tsx
  Client/src/app/contacts/components/ContactsTable.tsx
  Client/src/app/contacts/components/ContactsTableRow.tsx
  Client/src/app/contacts/page.tsx
  Client/src/app/documents/[documentId]/components/DocumentView.tsx
  Client/src/app/documents/[documentId]/components/InfoTable.tsx
  Client/src/app/documents/[documentId]/components/InfoTableRow.tsx
  Client/src/app/documents/components/ActionMenu.tsx
  Client/src/app/documents/components/CreateLink.tsx
  Client/src/app/documents/components/DocumentsTable.tsx
  Client/src/app/documents/components/DocumentsTableHeader.tsx
  Client/src/app/documents/components/DocumentsTableRow.tsx
  Client/src/app/documents/components/DragAndDropBox.tsx
  Client/src/app/documents/components/LinkDetailsAccordion.tsx
  Client/src/app/documents/page.tsx
  Client/src/app/layout/DropdownMenu.tsx
  Client/src/app/layout/Sidebar.tsx
  Client/src/app/links/[linkId]/components/FileAccessFormModal.tsx
  Client/src/app/links/[linkId]/components/FileAccessMessage.tsx
  Client/src/app/links/[linkId]/components/FileDisplay.tsx
  Client/src/app/links/[linkId]/layout.tsx
  Client/src/app/links/[linkId]/page.tsx
  Client/src/app/not-found.tsx
  Client/src/app/profile/components/PasswordForm.tsx
  Client/src/app/profile/components/ProfileClient.tsx
  Client/src/app/profile/components/ProfileForm.tsx
  Client/src/app/profile/page.tsx
  Client/src/app/settings/components/BrandingSetting.tsx
  Client/src/app/team/components/TeamClient.tsx
  Client/src/components/Breadcrumb.tsx
  Client/src/components/CustomCircularProgress.tsx
  Client/src/components/CustomUploader.tsx
  Client/src/components/FormInput.tsx
  Client/src/components/ModalWrapper.tsx
  Client/src/components/PageLoader.tsx
  Client/src/components/Paginator.tsx
  Client/src/components/PdfViewer.tsx
  Client/src/hooks/useFormSubmission.ts
  Client/src/providers/auth/AuthWrapper.tsx
  Client/src/utils/theme/globalTheme.ts
Labels: Bug, Refactor, Frontend, UX/UI Change

#178 Bug/design issues
  Client/.env
  Client/.gitignore
  Client/prisma/schema.prisma
  Client/prisma/seed.ts
  Client/src/app/auth/account-created/loading.tsx
  Client/src/app/auth/forgot-password/loading.tsx
  Client/src/app/auth/password-reset-confirm/loading.tsx
  Client/src/app/auth/reset-password/loading.tsx
  Client/src/app/auth/sign-in/loading.tsx
  Client/src/app/auth/sign-up/loading.tsx
  Client/src/app/contacts/loading.tsx
  Client/src/app/documents/[documentId]/loading.tsx
  Client/src/app/documents/loading.tsx
  Client/src/app/links/[linkId]/loading.tsx
  Client/src/app/loading.tsx
  Client/src/app/profile/components/ProfileForm.tsx
  Client/src/app/profile/loading.tsx
  Client/src/app/settings/loading.tsx
  Client/src/app/team/components/TeamClient.tsx
  Client/src/app/team/loading.tsx
  Client/src/components/LoadingSpinner.tsx
  Client/src/data/dummyContacts.ts
  Client/src/data/dummyDocuments.ts
  Client/src/data/dummyTeams.ts
  Client/src/hooks/useDocumentAnalytics.ts
Labels: Cleanup

#183 UI: fixes in user details form modal
  Client/src/app/links/[linkId]/components/FileAccessFormModal.tsx
Labels: 🧑‍💻Testing
