Repository bluewave-labs/datahall, pull requests merged in 2025-03, with the labels that each got.

#241 bug/fixing build warnings
  src/app/contacts/components/ContactsTable.tsx
  src/app/documents/components/DocumentsTable.tsx
  src/app/documents/components/DragAndDropBox.tsx
  src/app/links/[linkId]/components/FileAccessContainer.tsx
  src/components/common/Breadcrumb.tsx
  src/components/loaders/CustomCircularProgress.tsx
  src/components/modals/ModalWrapper.tsx
Labels: Refactor, Backend, Frontend, ⚡Important

#240 Deploy preview
  .env.example
  .eslintrc.json
  .gitignore
  .prettierignore
  .prettierrc
  .vscode/settings.json
  next.config.mjs
  package-lock.json
  package.json
  src/app/api/_services/authService.ts
  src/app/api/_services/emailService.ts
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/auth/__deprecatedAuth/register/route.ts
  src/app/api/auth/__deprecatedAuth/resetPass/route.ts
  src/app/api/auth/password/forgot/route.ts
  src/app/api/auth/register/route.ts
  src/app/api/contacts/route.ts
  src/app/api/documents/[documentId]/links/[linkId]/route.ts
  src/app/api/documents/[documentId]/links/route.ts
  src/app/api/documents/[documentId]/route.ts
  src/app/api/documents/[documentId]/visitors/route.ts
  src/app/api/documents/_deprecatedDocuments/[documentId]/links/[linkId]/route.ts
  src/app/api/documents/_deprecatedDocuments/[documentId]/links/route.ts
  src/app/api/documents/_deprecatedDocuments/[documentId]/route.ts
  src/app/api/documents/_deprecatedDocuments/[documentId]/visitors/route.ts
  src/app/api/documents/_deprecatedDocuments/list/route.ts
  src/app/api/documents/_deprecatedDocuments/upload/route.ts
  src/app/api/documents/route.ts
  src/app/api/profile/changePassword/route.ts
  src/app/api/profile/route.ts
  src/app/api/public_links/[linkId]/access/route.ts
  src/app/api/public_links/[linkId]/route.ts
  src/app/api/public_links/_deprecatedLinks/route.ts
  src/app/auth/check-email/page.tsx
  src/app/auth/components/ForgotPasswordEmail.tsx
  src/app/auth/components/WelcomeEmail.tsx
  src/app/contacts/components/ContactsTable.tsx
  src/app/documents/[documentId]/page.tsx
  src/app/documents/components/DocumentsTable.tsx
  src/app/documents/components/DragAndDropBox.tsx
  src/app/documents/components/SharingOptionsAccordion.tsx
  src/app/documents/page.tsx
  src/app/links/[linkId]/components/FileAccessContainer.tsx
  src/app/links/[linkId]/page.tsx
  src/app/team/components/TeamClient.tsx
  src/app/team/components/dummyTeams.ts
  src/components/common/Breadcrumb.tsx
  src/components/layout/BlueWaveLogo.tsx
  src/components/loaders/CustomCircularProgress.tsx
  src/components/modals/ModalWrapper.tsx
  src/lib/authOptions.ts
  src/lib/prisma.ts
Labels: New Feature, Refactor, Core, 🔥Critical

#232 Add React Query (Tanstack) for API call's and state management in client components
  package-lock.json
  package.json
  src/app/documents/components/DocumentsTable.tsx
  src/app/documents/components/DragAndDropBox.tsx
  src/app/providers.tsx
  src/hooks/documents/index.ts
  src/hooks/documents/useAddDocument.ts
  src/hooks/documents/useDeleteDocument.ts
  src/hooks/documents/useDocuments.ts
  src/providers/query/QueryProvider.tsx
Labels: New Feature, Frontend, ⚡Important

#244 Revert "Add React Query (Tanstack) for API call's and state management in client components "
  package-lock.json
  package.json
  src/app/documents/components/DocumentsTable.tsx
  src/app/documents/components/DragAndDropBox.tsx
  src/app/providers.tsx
  src/hooks/documents/index.ts
  src/hooks/documents/useAddDocument.ts
  src/hooks/documents/useDeleteDocument.ts
  src/hooks/documents/useDocuments.ts
  src/providers/query/QueryProvider.tsx
Labels: Wontfix, 🔥Critical

#242 Everything Prettier ✨
  .env.example
  .eslintrc.json
  .prettierignore
  .prettierrc
  package.json
  src/app/auth/account-created/loading.tsx
  src/app/auth/forgot-password/loading.tsx
  src/app/auth/page.tsx
  src/app/auth/password-reset-confirm/loading.tsx
  src/app/auth/reset-password/loading.tsx
  src/app/auth/sign-in/loading.tsx
  src/app/auth/sign-up/loading.tsx
  src/app/contacts/loading.tsx
  src/app/documents/[documentId]/components/FilterToggle.tsx
  src/app/documents/[documentId]/loading.tsx
  src/app/documents/loading.tsx
  src/app/links/[linkId]/loading.tsx
  src/app/loading.tsx
  src/app/not-authorized.tsx
  src/app/page.tsx
  src/app/profile/loading.tsx
  src/app/settings/components/SettingsTabs.tsx
  src/app/settings/loading.tsx
  src/app/team/components/FilterToggle.tsx
  src/app/team/loading.tsx
  src/app/team/page.tsx
  src/components/layout/BlueWaveLogo.tsx
  src/components/loaders/LoadingButton.tsx
  src/icons/files/AudioIcon.tsx
  src/icons/files/ExcelIcon.tsx
  src/icons/files/FileIcon.tsx
  src/icons/files/FilePlusIcon.tsx
  src/icons/files/ImageIcon.tsx
  src/icons/files/PDFIcon.tsx
  src/icons/files/PPTIcon.tsx
  src/icons/files/TextIcon.tsx
  src/icons/files/VideoIcon.tsx
  src/icons/files/WordIcon.tsx
  src/icons/files/ZIPIcon.tsx
  src/icons/general/CopyIcon.tsx
  src/icons/users/EmptyStateIcon.tsx
  tsconfig.json
Labels: Cleanup

#247 Fix Production Issues
  src/app/api/_services/storage/supabase/supabaseStorageProvider.ts
  src/app/api/documents/route.ts
  src/app/documents/components/ActionMenu.tsx
  src/app/documents/components/DocumentsTableRow.tsx
  src/app/documents/components/DragAndDropBox.tsx
Labels: 🔥Critical

#252 Fix/upload issues
  src/app/documents/components/DragAndDropBox.tsx
  src/app/profile/components/ProfileForm.tsx
Labels: Cleanup, 🔥Critical

#245 Add React Query (Tanstack) for API call's and state management in client components
  package-lock.json
  package.json
  src/app/documents/components/DocumentsTable.tsx
  src/app/documents/components/DragAndDropBox.tsx
  src/app/providers.tsx
  src/hooks/documents/index.ts
  src/hooks/documents/useAddDocument.ts
  src/hooks/documents/useDeleteDocument.ts
  src/hooks/documents/useDocuments.ts
  src/providers/query/QueryProvider.tsx
Labels: New Feature, Frontend, ⚡Important

#243 Restructure directory and file names for documents
  src/app/documentAccess/[linkId]/components/AccessError.tsx
  src/app/documentAccess/[linkId]/components/AccessPage.tsx
  src/app/documentAccess/[linkId]/components/FileDisplay.tsx
  src/app/documentAccess/[linkId]/components/VisitorInfoModal.tsx
  src/app/documentAccess/[linkId]/layout.tsx
  src/app/documentAccess/[linkId]/loading.tsx
  src/app/documentAccess/[linkId]/page.tsx
Labels: Cleanup, Refactor

#249 Adding TanStack Query to the contacts page
  src/app/contacts/components/ContactsTable.tsx
  src/app/documents/components/DocumentsTable.tsx
  src/app/documents/components/DragAndDropBox.tsx
  src/hooks/contacts/useFetchContacts.ts
  src/hooks/documents/index.ts
  src/hooks/documents/useFetchDocuments.ts
  src/hooks/documents/useUploadDocument.ts
  src/hooks/index.ts
Labels: New Feature, Refactor, Backend, Frontend

#253 Creating password form modal and improving profile form
  src/app/profile/components/PasswordForm.tsx
  src/app/profile/components/PasswordFormModal.tsx
  src/app/profile/components/ProfileClient.tsx
  src/app/profile/components/ProfileForm.tsx
  src/app/profile/page.tsx
  src/components/loaders/LoadingButton.tsx
  src/theme/globalTheme.ts
Labels: New Feature, Frontend, UX/UI Change

#256 Refactor profile page components and update global theme styles
  src/app/profile/components/PasswordForm.tsx
  src/app/profile/components/PasswordFormModal.tsx
  src/app/profile/components/ProfileClient.tsx
  src/app/profile/components/ProfileForm.tsx
  src/app/profile/page.tsx
  src/components/loaders/LoadingButton.tsx
  src/theme/globalTheme.ts
Labels: Duplicate, Refactor, UX/UI Change
