Repository bluewave-labs/datahall, pull requests merged in 2025-06, with the labels that each got.

#302 feat: enhance document and link analytics features
  package.json
  prisma/schema.prisma
  src/app/api/documents/[documentId]/analytics/route.ts
  src/app/api/documents/[documentId]/links/[linkId]/analytics/route.ts
  src/app/api/documents/[documentId]/links/route.ts
  src/app/api/public_links/[linkId]/analytics/route.ts
  src/app/documentAccess/[linkId]/components/AccessPage.tsx
  src/app/documentAccess/[linkId]/components/FileDisplay.tsx
  src/components/fileHandling/PDFViewer.tsx
  src/hooks/analytics/useCreateDocumentAnalytics.ts
  src/services/analyticsService.ts
  src/shared/enums.ts
  src/shared/queryKeys.ts
  src/shared/utils/fileUtils.ts
  src/shared/validation/documentSchemas.ts
  src/shared/validation/publicLinkSchemas.ts
Labels: Refactor, Backend, Frontend, 🔥Critical

#304 Refactor reusable modals and replace legacy modal usage with typed openModal pattern
  src/app/documents/[documentId]/components/InfoTableRow.tsx
  src/app/documents/components/ActionMenu.tsx
  src/app/documents/components/CreateLinkModal.tsx
  src/app/documents/components/DragAndDropBox.tsx
  src/app/profile/components/ProfileForm.tsx
  src/app/settings/components/BrandingSetting.tsx
  src/app/team/components/TeamClient.tsx
  src/components/modals/DeleteConfirmModal.tsx
  src/components/modals/InviteModal.tsx
  src/components/modals/UploadFileModal.tsx
  src/providers/modal/ModalRegistry.ts
Labels: 🧑‍💻Testing, New Feature, Refactor, Frontend

#306 Feature: Document Details Page
  public/pdf.worker.min.mjs
  src/app/api/documents/[documentId]/analytics/route.ts
  src/app/api/documents/[documentId]/links/[linkId]/log/route.ts
  src/app/api/public_links/[linkId]/analytics/route.ts
  src/app/contacts/components/ContactsTable.tsx
  src/app/documentAccess/[linkId]/components/AccessPage.tsx
  src/app/documentAccess/[linkId]/components/FileDisplay.tsx
  src/app/documentAccess/[linkId]/components/VisitorInfoModal.tsx
  src/app/documentAccess/[linkId]/layout.tsx
  src/app/documentAccess/[linkId]/page.tsx
  src/app/documents/[documentId]/components/CustomBarChart.tsx
  src/app/documents/[documentId]/components/DocumentView.tsx
  src/app/documents/[documentId]/components/FilterToggle.tsx
  src/app/documents/[documentId]/components/InfoTable.tsx
  src/app/documents/[documentId]/components/InfoTableHeader.tsx
  src/app/documents/[documentId]/components/InfoTableRow.tsx
  src/app/documents/[documentId]/components/LinkVisitorModal.tsx
  src/app/documents/[documentId]/page.tsx
  src/app/documents/components/CreateLink.tsx
  src/app/documents/components/DocumentsTable.tsx
  src/app/documents/components/DocumentsTableHeader.tsx
  src/app/documents/components/DocumentsTableRow.tsx
  src/app/team/components/UserTable.tsx
  src/components/fileHandling/PDFViewer.tsx
  src/components/navigation/Paginator.tsx
  src/hooks/data/documentAccess/useCreateDocumentAnalyticsMutation.ts
  src/hooks/data/documentAccess/useCreateLinkVisitorMutation.ts
  src/hooks/data/documentDetails/useAnalyticsQuery.ts
  src/hooks/data/documentDetails/useDocumentDetailQuery.ts
  src/hooks/data/documentDetails/useDocumentLinksQuery.ts
  src/hooks/data/documentDetails/useDocumentVisitorsQuery.ts
  src/hooks/data/documentDetails/useLinkVisitorsQuery.ts
  src/hooks/data/documents/useDocumentAnalyticsQuery.ts
  src/hooks/data/index.ts
  src/hooks/forms/useFormSubmission.ts
  src/hooks/index.ts
  src/hooks/ui/useResponsivePageSize.ts
  src/hooks/utils/useHashTab.ts
  src/hooks/utils/usePaginatedTable.ts
  src/hooks/utils/useSort.ts
  src/icons/files/DownloadIcon.tsx
  src/icons/files/FileDownloadIcon.tsx
  src/icons/index.ts
  src/services/analyticsService.ts
  src/services/email/emailService.ts
  src/services/index.ts
  src/services/linkService.ts
  src/services/storage/storageService.ts
  src/services/storage/supabase/supabaseStorageProvider.ts
  src/shared/models/analyticsModels.ts
  src/shared/models/index.ts
  src/shared/models/linkModels.ts
  src/shared/models/userModels.ts
  src/shared/queryKeys.ts
  src/shared/utils/exportToCsv.ts
  src/shared/utils/index.ts
  src/shared/validation/analyticsSchemas.ts
  src/shared/validation/documentSchemas.ts
  src/shared/validation/routeSchemas.ts
  src/theme/globalTheme.ts
Labels: Cleanup, New Feature, Refactor, Backend, Core, Frontend, 🔥Critical

#308 Refactor/modal management v2
  src/app/documents/[documentId]/components/InfoTableRow.tsx
  src/app/documents/components/ActionMenu.tsx
  src/app/documents/components/CreateLinkModal.tsx
  src/app/documents/components/DragAndDropBox.tsx
  src/app/documents/components/ShareableLinkModal.tsx
  src/app/profile/components/ProfileForm.tsx
  src/app/providers.tsx
  src/app/settings/components/BrandingSetting.tsx
  src/app/team/components/TeamClient.tsx
  src/components/common/AvatarCard.tsx
  src/components/layout/Sidebar.tsx
  src/components/modals/DeleteConfirmModal.tsx
  src/components/modals/InviteModal.tsx
  src/components/modals/ModalContainer.tsx
  src/components/modals/UploadFileModal.tsx
  src/providers/auth/AuthProvider.tsx
  src/providers/modal/ModalProvider.tsx
  src/providers/modal/ModalRegistry.ts
Labels: Cleanup, Refactor, Core, Frontend, 🌱Nice-to-Have

#317 🐞 Bug Fixes — Create Link, Link Table, Profile & Chart Sorting
  src/app/api/documents/[documentId]/links/[linkId]/route.ts
  src/app/documents/[documentId]/components/CustomBarChart.tsx
  src/app/documents/[documentId]/components/InfoTableRow.tsx
  src/app/documents/components/ActionMenu.tsx
  src/app/documents/components/SendingAccordion.tsx
  src/app/documents/components/SharingOptionsAccordion.tsx
  src/components/input/FormInput.tsx
  src/hooks/data/documentDetails/useDeleteLinkMutation.ts
  src/hooks/data/profile/useUpdatePasswordMutation.ts
  src/hooks/forms/useCreateLinkForm.ts
  src/hooks/utils/useSort.ts
  src/shared/models/profileModels.ts
  src/shared/validation/documentLinkSchemas.ts
Labels: Backend, Core, Frontend, 🔥Critical

#320 Document Access Modal System Refactor & Full Public Flow Integration
  src/app/api/public_links/[linkId]/access/route.ts
  src/app/api/public_links/[linkId]/route.ts
  src/app/documentAccess/[linkId]/components/AccessError.tsx
  src/app/documentAccess/[linkId]/components/AccessManager.tsx
  src/app/documentAccess/[linkId]/components/AccessPage.tsx
  src/app/documentAccess/[linkId]/components/AccessSkeleton.tsx
  src/app/documentAccess/[linkId]/components/DocumentAccessModal.tsx
  src/app/documentAccess/[linkId]/components/FileDisplay.tsx
  src/app/documentAccess/[linkId]/layout.tsx
  src/app/documentAccess/[linkId]/oldPage.tsx
  src/app/documentAccess/[linkId]/page.tsx
  src/app/documents/[documentId]/components/DocumentView.tsx
  src/app/documents/[documentId]/components/InfoTableRow.tsx
  src/app/documents/[documentId]/components/VisitorLogModal.tsx
  src/hooks/data/documentAccess/useDocumentAccessQuery.ts
  src/hooks/data/documentAccess/useLinkAccess.ts
  src/hooks/data/documentAccess/usePublicLinkMeta.ts
  src/hooks/forms/useDocumentAccessForm.ts
  src/services/linkService.ts
  src/shared/models/linkModels.ts
  src/shared/validation/documentAccessSchemas.ts
  src/shared/validation/publicLinkSchemas.ts
Labels: Cleanup, New Feature, Backend, Frontend, UX/UI Change, 🔥Critical
