Repository bluewave-labs/datahall, pull requests merged in 2025-02, with the labels that each got.

#193 Change branding from dataroom to datahall
  Client/package-lock.json
  Client/package.json
  Client/src/app/documents/page.tsx
  Client/src/app/layout.tsx
  Client/src/app/settings/components/BrandingSetting.tsx
Labels: Refactor

#194 Avoid API call for each document while rendering documents table
  Client/src/app/documents/components/DocumentsTableRow.tsx
Labels: 🧑‍💻Testing, Refactor

#209 API Refactoring & Backend Services Reorganization
  prisma/schema.prisma
  src/app/api/_services/authService.ts
  src/app/api/_services/emailService.ts
  src/app/api/_services/errorService.ts
  src/app/api/_services/index.ts
  src/app/api/_services/linkService.ts
  src/app/api/_services/storage/supabase/supabaseStorageProvider.ts
  src/app/api/_services/storageService.ts
  src/app/api/auth/[...nextauth]/route.ts
  src/app/api/auth/__deprecatedAuth/[...nextauth]/route.ts
  src/app/api/auth/__deprecatedAuth/register/route.ts
  src/app/api/auth/__deprecatedAuth/resetPass/route.ts
  src/app/api/auth/__deprecatedAuth/resetPassForm/route.ts
  src/app/api/auth/__deprecatedAuth/verify-email/route.ts
  src/app/api/auth/password/forgot/route.ts
  src/app/api/auth/password/reset/route.ts
  src/app/api/auth/register/route.ts
  src/app/api/auth/verify/route.ts
  src/app/api/contacts/route.ts
  src/app/api/documents/[documentId]/links/[linkId]/route.ts
  src/app/api/documents/[documentId]/links/route.ts
  src/app/api/documents/[documentId]/route.ts
  src/app/api/documents/[documentId]/visitors/route.ts
  src/app/api/documents/_deprecatedDocuments/[documentId]/links/[linkId]/route.ts
  src/app/api/documents/_deprecatedDocuments/[documentId]/links/route.ts
  src/app/api/documents/_deprecatedDocuments/[documentId]/route.ts
  src/app/api/documents/_deprecatedDocuments/[documentId]/visitors/route.ts
  src/app/api/documents/_deprecatedDocuments/list/route.ts
  src/app/api/documents/_deprecatedDocuments/upload/route.ts
  src/app/api/documents/route.ts
  src/app/api/profile/changeName/route.ts
  src/app/api/profile/changePassword/route.ts
  src/app/api/profile/route.ts
  src/app/api/public_links/[linkId]/access/route.ts
  src/app/api/public_links/[linkId]/route.ts
  src/app/auth/account-created/page.tsx
  src/app/auth/forgot-password/page.tsx
  src/app/auth/reset-password/page.tsx
  src/app/documents/components/ActionMenu.tsx
  src/app/documents/components/CreateLink.tsx
  src/app/documents/components/DocumentsTable.tsx
  src/app/documents/components/DragAndDropBox.tsx
  src/app/documents/components/ShareableLinkDialog.tsx
  src/app/documents/components/SharingOptionsAccordion.tsx
  src/app/links/[linkId]/components/FileAccessContainer.tsx
  src/app/links/[linkId]/components/FileAccessFormModal.tsx
  src/app/not-found.tsx
  src/app/providers.tsx
  src/components/CustomUploader.tsx
  src/config/routesConfig.ts
  src/hooks/useDocumentData.ts
  src/servicesTemp_UntilTanstack/documentService.ts
  src/servicesTemp_UntilTanstack/linkService.ts
  src/shared/models/models.ts
Labels: Cleanup, Refactor, Backend, Core
